name: Julian Mark Events
favicon: null
layout_spectrum: 0.5313088016118854
typography_spectrum: 0.4748674219008535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.14643267821520567
  lightness: 0.7260974738746881
  saturation: 0.8738536110613495
  rhythmicContrast: 0.8868367741815746
purpose: []
